/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-07-10 07:20:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/slider/sliderDisplay.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/slider/sliderOption.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/commons/clock.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/commons/card.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/commons/cheer.css\" />\r\n");
      out.write(" <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write(" <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/slider/jquery.slides.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <!-- 팝업 -->\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/css/swiper.min.css\">\r\n");
      out.write(" <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper.min.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\t.lastRow{\r\n");
      out.write("\t\tmargin-bottom: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\tli{\r\n");
      out.write("\t\tlist-style-type:none;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tol a{\r\n");
      out.write("\t\tpadding-left:21px;\r\n");
      out.write("\t\tpadding-right: 40px;\r\n");
      out.write("\t}\r\n");
      out.write("  \tspan#popup1{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t    background-image:url(\"");
      out.print(request.getContextPath());
      out.write("/manager/popup/1\"); \r\n");
      out.write("\t    background-repeat: no-repeat;\r\n");
      out.write("\t    background-position: center;\r\n");
      out.write("\t    background-size: cover;\r\n");
      out.write("\t    z-index: 98;\r\n");
      out.write("\t}\r\n");
      out.write("\tspan#popup2{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t    background-image:url(\"");
      out.print(request.getContextPath());
      out.write("/manager/popup/2\");\r\n");
      out.write("\t    background-repeat: no-repeat;\r\n");
      out.write("\t    background-position: center;\r\n");
      out.write("\t    background-size: cover;\r\n");
      out.write("\t    z-index: 99;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tspan#popup3{\t\t\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t     background-image:url(\"");
      out.print(request.getContextPath());
      out.write("/manager/popup/3\");\r\n");
      out.write("\t    background-repeat: no-repeat;\r\n");
      out.write("\t    background-position: center;\r\n");
      out.write("\t    background-size: cover;\r\n");
      out.write("\t    z-index: 98;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv#count_consult_end{\r\n");
      out.write("\t\tdisplay:none;\r\n");
      out.write("\t\tbackground-color: lavenderblush;\r\n");
      out.write("\t\tposition:fixed; \r\n");
      out.write("\t\tfont-size:22px;\r\n");
      out.write("\t\tborder:gold 6px double;\r\n");
      out.write("\t\twidth:500px;\r\n");
      out.write("\t\theight:127px;\r\n");
      out.write("\t\ttop: 776px;\r\n");
      out.write("   \t\tleft: 1359px;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tz-index:99;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tdisplay:flex; \r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("   \t\t color: lightcoral;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.swiper-container {\r\n");
      out.write("\tz-index: 99;\r\n");
      out.write("    left: 109px;\r\n");
      out.write("    top: 321px;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    width: 420px;\r\n");
      out.write("    height: 595px;  \r\n");
      out.write("    border: 5px double #523700;\r\n");
      out.write("    border-radius: 7px;\r\n");
      out.write("    box-shadow: 0 0 20px #ccc inset;\r\n");
      out.write("\t}\r\n");
      out.write("\t.swiper-slide {\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tdisplay:flex; /* 내용을 중앙정렬 하기위해 flex 사용 */\r\n");
      out.write("\t\talign-items:center; /* 위아래 기준 중앙정렬 */\r\n");
      out.write("\t\tjustify-content:center; /* 좌우 기준 중앙정렬 */\r\n");
      out.write("\t}\r\n");
      out.write("\t.swiper-slide img {\r\n");
      out.write("\t\tbox-shadow:0 0 5px #555;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.noticeWrap li,.lectureReviewWrap li ,.foundedReviewWrap li ,.lectureWrap li ,.recommendWrap li{\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t    text-overflow: ellipsis;\r\n");
      out.write("\t    white-space: nowrap;\r\n");
      out.write("\t}\r\n");
      out.write("\t.noticeDate{\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t\tmargin-right: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.mainTotalCheer{\r\n");
      out.write("\t    margin-left: 33px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.popupclose{\r\n");
      out.write("\t\tfont-size: 45px;\r\n");
      out.write("\t\tposition: fixed;\r\n");
      out.write("\t\tz-index: 99;\r\n");
      out.write("\t\tleft: 494px;\r\n");
      out.write("   \t\ttop: 861px;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t.popupclose2{\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t    position: fixed;\r\n");
      out.write("\t    z-index: 99;\r\n");
      out.write("        left: 335px;\r\n");
      out.write("    \ttop: 880px;\r\n");
      out.write("\t    cursor: pointer;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("\tli a{\r\n");
      out.write("\t    overflow: hidden;\r\n");
      out.write("    \ttext-overflow: ellipsis;\r\n");
      out.write("\t}\r\n");
      out.write("\tli span{\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("    \tmargin-right: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.cardtitdetailWrap li{\r\n");
      out.write("\t\tfont-size: 1.4em;\r\n");
      out.write("\t}\r\n");
      out.write("\t.cardtitdetailWrap li span{\r\n");
      out.write("\t\tfont-size: 0.8em;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\t\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t  <div id=\"slides\">\r\n");
      out.write("\t    <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/images/corona19banner.jpg\">\r\n");
      out.write("\t    <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/images/banner2.jpg\">\r\n");
      out.write("\t    <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/images/corona19banner2.jpg\">\r\n");
      out.write("\t    <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/images/successSeminarbanner.jpg\">\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-offset-1 col-xs-10 cheerUpWrap\" >\r\n");
      out.write("\t\t\t\t<div class=\"cheerUpTitle\">\r\n");
      out.write("\t\t\t\t\t<h3>서로에게 <span style=\"color: blue;\">응원을!</span></h3>\r\n");
      out.write("\t\t\t\t\t<span class=\"mainTotalCheer\">전체 : 건</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"cheerUpText\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"cheerUpText\"><button type=\"button\" onclick=\"CheerUpload();\" class=\"btn btn-primary\">응원하기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-offset-1 col-xs-2\">\r\n");
      out.write("\t\t\t\t<div class=\"clock\">\r\n");
      out.write("\t\t\t\t\t<div class=\"date_box \" style=\"font-size: 2.2em;text-align: center;padding-top: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"year\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"point\"></span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"moths\" style=\"font-size: 0.6em;\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"month\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"point\">월</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dates\" style=\"font-size: 1.6em;\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"date\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"point\">일</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"time_box\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"txt_lg\" id=\"hours\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"mark01\">:</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"txt_lg\" id=\"min\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"mark02\">.</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"txt_sm\" id=\"sec\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-8 dateViewer\">\r\n");
      out.write("\t\t\t\t<div class=\"cheer\" style=\"overflow: hidden; position: relative; height: 100%;\">\r\n");
      out.write("\t\t\t\t\t<ul id=\"cheerList\" class=\"cheerList\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t  \t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-4 col-xs-4\"  style=\"height:180px; border-radius: 26px; margin: 10px 20px 10px 30px; \">\r\n");
      out.write("\t\t\t\t<div class=\"card-body noticeWrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"cardtitleWrap\">\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"cardol\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-bullhorn fa-2x\" aria-hidden=\"true\"></i> <span class=\"cardTitle\">공지사항</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"cardoP\"><a href=\"/board/notice/list\">더 보기&nbsp; ></a></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"cardtitdetailWrap scrollbars\">\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t \t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/main.jsp(207,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main.jsp(207,8) '${noticeList }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${noticeList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/main.jsp(207,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("notice");
      // /WEB-INF/views/main.jsp(207,8) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(0);
      // /WEB-INF/views/main.jsp(207,8) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(9);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<li>\r\n");
            out.write("\t\t\t\t\t\t\t\t<a class=\"col-sm-8\" href=\"");
            out.print(request.getContextPath() );
            out.write("/board/notice/detail?notice_no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.notice_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.notice_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t<span class=\"noticeDate\">");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return;
            out.write("</span>\r\n");
            out.write("\t\t\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      }
      out.write("</ol> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-7\" style=\"height: 180px; border-radius: 26px; margin: 10px;\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body recommendWrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"cardtitleWrap\">\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"cardol\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-list fa-2x\" aria-hidden=\"true\"></i><span class=\"cardTitle\"> 창업뉴스</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"cardtitdetailWrap scrollbars\">\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t</ol> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div class=\"row lastRow\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-4\" style=\"height:180px; border-radius: 26px; margin: 10px 20px 10px 30px;\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body lectureWrap\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cardtitleWrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<ol class=\"cardol\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"fa fa-calendar fa-2x\" aria-hidden=\"true\"></i><span class=\"cardTitle\"> 이달의 모집과정</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"cardoP\"><a href=\"/lecture/list\">더 보기&nbsp; ></a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cardtitdetailWrap scrollbars\">\r\n");
      out.write("\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t</ol> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-4\" style=\"height: 180px; border-radius: 26px; margin: 10px; \">\r\n");
      out.write("\t\t\t\t<div class=\"card-body lectureReviewWrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"cardtitleWrap\">\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"cardol\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-graduation-cap fa-2x\" aria-hidden=\"true\"></i><span class=\"cardTitle\"> 수강 후기</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"cardoP\"><a href=\"/lecture/review/list\">더 보기&nbsp; ></a></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"cardtitdetailWrap scrollbars\">\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t</ol> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-3\" style=\"height: 180px; border-radius: 26px; margin: 10px;\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body foundedReviewWrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"cardtitleWrap\">\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"cardol\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-commenting fa-2x\" aria-hidden=\"true\"></i><span class=\"cardTitle\"> 창업 후기</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"cardoP\"><a href=\"/board/foundReviewList\" data-transition=\"fade\">더 보기&nbsp; ></a></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"cardtitdetailWrap scrollbars\">\r\n");
      out.write("\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t</ol> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t <!-- 팝업 -->\r\n");
      out.write("\t<!-- <span id=\"popup3\">\r\n");
      out.write("\t\t<input id=\"popup3close\" value=\"비활성화\" type=\"image\" src=\"/resources/images/x2.png\" style=\"float: right; width: 12px;visibility: visible;\">\r\n");
      out.write("\t</span>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<span id=\"popup2\">\r\n");
      out.write("\t\t<input id=\"popup2close\" value=\"비활성화\" type=\"image\" src=\"/resources/images/x2.png\" style=\"float: right; width: 12px;visibility: visible;\">\r\n");
      out.write("\t</span>\r\n");
      out.write("\t<span id=\"popup1\">\r\n");
      out.write("\t\t<input id=\"popup1close\" value=\"비활성화\" type=\"image\" src=\"/resources/images/x2.png\" style=\"float: right; width: 12px;visibility: visible;\">\r\n");
      out.write("\t</span>  -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 상담문의 완료 알림 -->\r\n");
      out.write("\t<div id=\"count_consult_end\" class=\"col-sm-12\" style=\"display:none;\" >\r\n");
      out.write("\t\t<div  id=\"count_consult_end2\" class =\"col-sm-12\"  onclick=\"location.href ='http://localhost/board/consult/list'\" style=\"cursor:pointer;display: table;` padding-left: 95px; \">\r\n");
      out.write("\t\t\t<input id=\"popupclose\" type=\"image\" src=\"/resources/images/letter.png\" style=\"width: 77px; position: FIXED; padding-top: 25px;\">\r\n");
      out.write("\t\t\t<div id=\"count_consult_end_text\" style=\"display:table-cell; vertical-align: middle;padding-top: 40px; padding-left: 95px;\" ></div>\r\n");
      out.write("\t\t</div>\t\t\t\t\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 팝업 알림 -->\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("<script src=\"/resources/js/cookie.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar userId=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t\t//상담완료 글\r\n");
      out.write("\t\t/* alert(count_consult_end); */\r\n");
      out.write("\t\tif(count_consult_end>0){\r\n");
      out.write("\t\t\t/* $('#count_consult_end').css({'visibility':'visible'}); */\r\n");
      out.write("\t\t\t$('#count_consult_end_text').text(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count_consult_end}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("+'개의 완료된 상담글이 있습니다.');\r\n");
      out.write("\t\t\t$(\"#count_consult_end\").fadeIn(4000);\r\n");
      out.write("\t\t\t$(\"#count_consult_end\").fadeOut(15000); \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#count_consult_end').css({'visibility':'hidden'});\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t/* $('#count_consult_end').on('click',function(){\r\n");
      out.write("\t\t$('#count_consult_end').hide();\r\n");
      out.write("\t}); */\t\r\n");
      out.write("\t\r\n");
      out.write("\t//팝업닫기\r\n");
      out.write("\t$('.popupclose').on('click',function(){\r\n");
      out.write("\t\t$('.swiper-container').hide();\r\n");
      out.write("\t}); \r\n");
      out.write("\t//팝업 오늘은 그만보기\r\n");
      out.write("\t$('.popupclose2').on('click',function() {\r\n");
      out.write("    \tsetCookie('todayClose','Y', 1);\r\n");
      out.write("        $(\".swiper-container\").hide();\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\tif(getCookie(\"todayClose\")!=\"Y\"){\r\n");
      out.write("\t    $(\".swiper-container\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction setCookie(cookieName, value, exdays){\r\n");
      out.write("\t    var exdate = new Date();\r\n");
      out.write("\t    exdate.setDate(exdate.getDate() + exdays);\r\n");
      out.write("\t    var cookieValue = escape(value) + ((exdays==null) ? \"\" : \"; expires=\" + exdate.toGMTString());\r\n");
      out.write("\t    document.cookie = cookieName + \"=\" + cookieValue;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction deleteCookie(cookieName){\r\n");
      out.write("\t    var expireDate = new Date();\r\n");
      out.write("\t    expireDate.setDate(expireDate.getDate() - 1);\r\n");
      out.write("\t    document.cookie = cookieName + \"= \" + \"; expires=\" + expireDate.toGMTString();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getCookie(cookieName) {\r\n");
      out.write("\t    cookieName = cookieName + '=';\r\n");
      out.write("\t    var cookieData = document.cookie;\r\n");
      out.write("\t    var start = cookieData.indexOf(cookieName);\r\n");
      out.write("\t    var cookieValue = '';\r\n");
      out.write("\t    if(start != -1){\r\n");
      out.write("\t        start += cookieName.length;\r\n");
      out.write("\t        var end = cookieData.indexOf(';', start);\r\n");
      out.write("\t        if(end == -1)end = cookieData.length;\r\n");
      out.write("\t        cookieValue = cookieData.substring(start, end);\r\n");
      out.write("\t    }\r\n");
      out.write("\t    return unescape(cookieValue);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tnew Swiper('.swiper-container', {\r\n");
      out.write("\t\t/* effect : 'fade', */\r\n");
      out.write("\t\tloop : true,// 슬라이드 반복\r\n");
      out.write("\t\tautoplay: 1000,\r\n");
      out.write("\t\t// 자동높이 사용여부 : 사용하지 않을시 기본값은 false\r\n");
      out.write("\t\t/* autoHeight : true, */\r\n");
      out.write("\t\tpagination : { // 페이징 설정\r\n");
      out.write("\t\t\tel : '.swiper-pagination',\r\n");
      out.write("\t\t\tclickable : true, // 페이징을 클릭하면 해당 영역으로 이동, 필요시 지정해 줘야 기능 작동\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tnavigation : { // 네비게이션 설정\r\n");
      out.write("\t\t\tnextEl : '.swiper-button-next', // 다음 버튼 클래스명\r\n");
      out.write("\t\t\tprevEl : '.swiper-button-prev', // 이번 버튼 클래스명\r\n");
      out.write("\t\t},\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\t//응원글 리스트 가져오는 기능\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"/cheerList\",\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\tsuccess :function(suc){\r\n");
      out.write("\t\t\tcheerListMaker(suc);\r\n");
      out.write("\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(err){\r\n");
      out.write("\t\t\talert(\"에러\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t//응원글 리스트 만드는 기능 \r\n");
      out.write("\tfunction cheerListMaker(data){\r\n");
      out.write("\t\t$(\".cheerUpTitle span:last\").text(\"전체 :\"+data.cheerCnt+\"건\")\r\n");
      out.write("\t\tfor(var i= 0; i<data.memberList.length; i++){\r\n");
      out.write("\t\tvar li= $(\"<li></li>\");\r\n");
      out.write("\t\t\tvar member= data.memberList[i];\r\n");
      out.write("\t\t\tvar cheer= data.cheerList[i];\r\n");
      out.write("\t\t\tvar photoDiv= $(\"<div class='photo'></div>\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar studentInfoDiv= $(\"<div class='studentInfo'></div>\")\r\n");
      out.write("\t\t\tvar member_idhidden= $(\"<input type='hidden' name=\"+member.member_id+\" value=\"+member.member_id+\">\");\r\n");
      out.write("\t\t\tvar member_idSpan= $(\"<span>\"+member.member_id+\"</span>\");\r\n");
      out.write("\t\t\tvar member_nameSpan= $(\"<span>\"+member.member_name+\"</span>\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar boundarySpan= $(\"<span class='boundary'>|</span>\");\r\n");
      out.write("\t\t\tvar cheerTextP= $(\"<p class='cheerText'>\"+cheer.cheer_content+\"</p>\");\r\n");
      out.write("\t\t\tvar dateWrapDiv= $(\"<div class='dateWrap'></div>\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar  day = new Date(cheer.cheer_regdate);\r\n");
      out.write("\t\t\tvar date=day.format(\"yyyy-MM-dd\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar cheerdateP = $(\"<p class='cheerdate'>\"+date+\"</p>\")\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tli.append(photoDiv);\r\n");
      out.write("\t\t\tli.append(studentInfoDiv);\r\n");
      out.write("\t\t\tli.append(boundarySpan);\r\n");
      out.write("\t\t\tli.append(cheerTextP);\r\n");
      out.write("\t\t\tli.append(dateWrapDiv);\r\n");
      out.write("\t\t\tstudentInfoDiv.append(member_idhidden);\r\n");
      out.write("\t\t\tstudentInfoDiv.append(member_idSpan);\r\n");
      out.write("\t\t\tstudentInfoDiv.append(member_nameSpan);\r\n");
      out.write("\t\t\tdateWrapDiv.append(boundarySpan);\r\n");
      out.write("\t\t\tdateWrapDiv.append(cheerdateP);\r\n");
      out.write("\t\t\t/* var pictureStr = member.member_picture; */\r\n");
      out.write("\t\t\tphotoDiv.css({\"background-image\":\"url(");
      out.print(request.getContextPath());
      out.write("/commons/images/\"+member.member_id+\")\"});\r\n");
      out.write("\t\t\t$(\"#cheerList\").append(li);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//응원글 슬라이드 처리 부분\r\n");
      out.write("\tfunction tick2(){ \r\n");
      out.write("\t\t$('#cheerList li:first').slideUp( function () { $(this).appendTo($('#cheerList')).slideDown(); });\r\n");
      out.write("\t}\r\n");
      out.write("\t\tvar interval=setInterval(function(){ tick2 () }, 3000);\r\n");
      out.write("\t\r\n");
      out.write("\t$('#cheerList').hover(function(){\t//mousehover 시 멈춤 \r\n");
      out.write("\t\tclearInterval(interval);\r\n");
      out.write("\t},\r\n");
      out.write("\tfunction(){//mouseout 시 재시작\r\n");
      out.write("\t\tinterval=setInterval(function(){ tick2 () }, 3000);\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"/lecture/review/quickList\",\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\tsuccess:function(suc){\r\n");
      out.write("\t\t\tnewlectureReviewList(suc);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(err){\r\n");
      out.write("\t\t\talert(\"newFoundedReviewList 에러\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t function newlectureReviewList(lectureReview){\r\n");
      out.write("\t\tfor(var i=0; i<lectureReview.length; i++){\r\n");
      out.write("\t\t\tvar li = $(\"<li></li>\");\r\n");
      out.write("\t\t\tvar lecture= lectureReview[i];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar aTeg=$(\"<a class='col-sm-8'>\"+lecture.lecture_review_title+\"</a>\");\r\n");
      out.write("\t\t\tvar spanTeg=$(\"<span>\"+moment(lecture.lecture_review_regdate).format(\"YYYY-MM-DD\")+\"</span>\");\r\n");
      out.write("\t\t\taTeg.attr({\"href\":\"");
      out.print(request.getContextPath());
      out.write("/lecture/review/detail?lecture_review_no=\"+lecture.lecture_review_no+\"\"});\r\n");
      out.write("\t\tli.append(aTeg);\r\n");
      out.write("\t\tli.append(spanTeg);\r\n");
      out.write("\t\t$(\".lectureReviewWrap ol:last\").append(li)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} \r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"/foundedReviewList\",\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\tsuccess:function(suc){\r\n");
      out.write("\t\t\tnewFoundedReviewList(suc);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(err){\r\n");
      out.write("\t\t\talert(\"newFoundedReviewList 에러\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\t//창업후기 리스트 만드는 기능\r\n");
      out.write("\t function newFoundedReviewList(foundedList){\r\n");
      out.write("\t\tfor(var i=0; i<foundedList.length; i++){\r\n");
      out.write("\t\t\tvar li = $(\"<li></li>\");\r\n");
      out.write("\t\t\tvar found= foundedList[i];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar aTeg=$(\"<a class='col-sm-7'>\"+found.founded_review_title+\"</a>\");\r\n");
      out.write("\t\t\tvar spanTeg=$(\"<span>\"+moment(found.founded_review_regdate).format(\"YYYY-MM-DD\")+\"</span>\");\r\n");
      out.write("\t\t\taTeg.attr({\"href\":\"");
      out.print(request.getContextPath());
      out.write("/board/foundedReview/detail?founded_review_no=\"+found.founded_review_no+\"\"});\r\n");
      out.write("\t\tli.append(aTeg);\r\n");
      out.write("\t\tli.append(spanTeg);\r\n");
      out.write("\t\t$(\".foundedReviewWrap ol:last\").append(li)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"/news\",\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tsuccess:function(suc){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tnewsList(suc);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(err){\r\n");
      out.write("\t\t\talert(\"에러\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t //뉴스 리스트 만드는 기능\r\n");
      out.write("\t function newsList(obj){\r\n");
      out.write("\t\tvar newsList=obj.items;\r\n");
      out.write("\t\tfor(var i=0; i<newsList.length; i++){\r\n");
      out.write("\t\t\tvar li = $(\"<li></li>\");\r\n");
      out.write("\t\t\tvar news= newsList[i];\r\n");
      out.write("\t\t\tvar aTeg=$(\"<a class='col-sm-9'>\"+news.title+\"</a>\");\r\n");
      out.write("\t\t\tvar spanTeg=$(\"<span>\"+moment(news.pubDate).format(\"YYYY-MM-DD\")+\"</span>\");\r\n");
      out.write("\t\t\taTeg.attr({\"href\":news.originallink});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tli.append(aTeg);\r\n");
      out.write("\t\tli.append(spanTeg);\r\n");
      out.write("\t\t$(\".recommendWrap ol:last\").append(li)\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"/lectureThisMonth\",\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\tsuccess:function(suc){\r\n");
      out.write("\t\t\tlectureThisMonthList(suc);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(err){\r\n");
      out.write("\t\t\talert(\"에러\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t//모집강의 리스트 기능\r\n");
      out.write(" \tfunction lectureThisMonthList(obj){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar startDay=obj[0].lecture_recruit_date;\r\n");
      out.write("\t\tvar endDay=obj[0].lecture_recruit_status;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar startDate= new Date(startDay);\r\n");
      out.write("\t\tvar endDate= new Date(endDay);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar formatStartDate=startDate.format('yyyy.MM.dd');\r\n");
      out.write("\t\tvar formatEndDate=endDate.format('yyyy.MM.dd');\r\n");
      out.write("\t\tvar title= obj[0].lecture_title;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var i=0; i<obj.length; i++){\r\n");
      out.write("\t\t\tvar li = $(\"<li></li>\");\r\n");
      out.write("\t\t\tvar lecture= obj[i];\r\n");
      out.write("\t\t\tvar aTeg=$(\"<a class='col-sm-5'>\"+lecture.lecture_title+\"</a>\");\r\n");
      out.write("\t\t\tvar spanTeg=$(\"<span>\"+formatStartDate+\" ~ \"+formatEndDate+\"</span>\");\r\n");
      out.write("\t\t\taTeg.attr({\"href\":\"/lecture/detail?lecture_no=\"+lecture.lecture_no});\r\n");
      out.write("\t\t\tli.append(aTeg);\r\n");
      out.write("\t\t\tli.append(spanTeg);\r\n");
      out.write("\t\t\t$(\".lectureWrap ol:last\").append(li)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}  \r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/commons/cheer.js\"></script>\t\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/commons/clock.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/commons/slider.js\"></script>\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/main.jsp(210,33) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.notice_regdate }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /WEB-INF/views/main.jsp(210,33) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy.MM.dd");
    int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/main.jsp(300,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty popup.popup1 && not empty popup.popup2 && not empty popup.popup3}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<div class=\"swiper-container\" style=\"display: none;\">\r\n");
        out.write("\t\t\t<!-- <input id=\"popupclose\" type=\"image\" src=\"/resources/images/x2.png\" style=\"width: 42px; position: FIXED; left: 402px; top: 280px; z-index: 120;float: right; visibility: visible;\"> -->\r\n");
        out.write("\t\t\t<span class=\"popupclose\">&times;</span>\r\n");
        out.write("\t\t\t<span class=\"popupclose2\">오늘하루열지않음</span>\r\n");
        out.write("\t\t\t<div class=\"swiper-wrapper\">\r\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("</div>\r\n");
        out.write("\t\t\t\t\t\r\n");
        out.write("\t\t\t<!-- 네비게이션 버튼 -->\r\n");
        out.write("\t\t\t<div class=\"swiper-button-next\"></div><!-- 다음 버튼 (오른쪽에 있는 버튼) -->\r\n");
        out.write("\t\t\t<div class=\"swiper-button-prev\"></div><!-- 이전 버튼 -->\r\n");
        out.write("\t\t\r\n");
        out.write("\t\t\t<!-- 페이징 -->\r\n");
        out.write("\t\t\t<div class=\"swiper-pagination\"></div>\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/views/main.jsp(306,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty popup.popup1}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<span class=\"swiper-slide\" id=\"popup1\"></span>\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/views/main.jsp(309,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty popup.popup2}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<span class=\"swiper-slide\" id=\"popup2\"></span>\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/views/main.jsp(312,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty popup.popup3}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<span class=\"swiper-slide\" id=\"popup3\"></span>\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }
}
