/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-07-09 02:20:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.pds.document;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class documentDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<link href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/qna/detail.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/filedownload/jquery.fileDownload.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".btn-default{\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("}\r\n");
      out.write("</style>\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<form id=\"infoForm\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t<div style=\"width: 100%;\">\r\n");
      out.write("\t<table class=\"board_view\">\r\n");
      out.write("\t\t<colgroup>\r\n");
      out.write("\t\t\t<col width=\"15%\"/>\r\n");
      out.write("\t\t\t<col width=\"35%\"/>\r\n");
      out.write("\t\t\t<col width=\"15%\"/>\r\n");
      out.write("\t\t\t<col width=\"35%\"/>\r\n");
      out.write("\t\t</colgroup>\r\n");
      out.write("\t\t<caption style=\"font-size: 3.0em; margin-top:10px;\">문서자료</caption>\r\n");
      out.write("\r\n");
      out.write("\t\t<caption style=\"text-align:right;\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"btns\" id=\"updateBtn\">수정</a>\r\n");
      out.write("\t\t\t<a href=\"#\" onclick=\"toList();\" class=\"btns\" >목록으로</a>\r\n");
      out.write("\t\t</caption>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th scope=\"row\">제목</th>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" ><input name=\"document_title\" style=\"border: none; width: 100%;\" readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${document.document_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"document_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${document.document_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th scope=\"row\">첨부 파일</th>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"custom-file-upload\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name =\"originalName\" id=\"originalName\"style=\"border: none; width: 95%;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${document.originalName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"download\" style=\"background-color: #6b9ab8; color: white; border: 2px solid #6b9ab8\" >다운로드</button>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t    \t</td>\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\t<div class=\"col-xs-12  g_value\" style=\"min-height: 250px; padding: 8px 3px 3px; margin: 0px; overflow: auto;\">\r\n");
      out.write("\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${document.document_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<br></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<form id=\"jobForm\">\r\n");
      out.write("\t<input type='hidden' name=\"page\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type='hidden' name=\"perPageNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.perPageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("\t<input type='hidden' name=\"searchType\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.searchType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type='hidden' name=\"keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.keyword }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<input type='hidden' id=\"fileName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${document.document_dataVO.document_data_filename }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<input type='hidden' id=\"filePath\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${document.document_dataVO.document_data_path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\twindow.onload = function() {\r\n");
      out.write("\r\n");
      out.write("\t    setTimeout (function () {\r\n");
      out.write("\r\n");
      out.write("\t    scrollTo(0,0);\r\n");
      out.write("\r\n");
      out.write("\t    }, 100);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction toList(){\r\n");
      out.write("\t\tvar form = $('#infoForm');\r\n");
      out.write("\t\tform.attr('action','list');\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t};\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('#updateBtn').on('click', function(e) {\r\n");
      out.write("\t\tvar form = $('#infoForm');\r\n");
      out.write("\t\tform.attr('action','modifyForm');\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t$('#download').on('click', function(e){\r\n");
      out.write("\t\tvar fileName = $('#fileName').val();\r\n");
      out.write("\t\tvar path = $('#filePath').val();\r\n");
      out.write("\t\tvar downloadName = $('#originalName').val();\r\n");
      out.write("\t\tvar file = { \"fileName\": fileName, \"filePath\": path, \"downloadName\":downloadName };\r\n");
      out.write("\r\n");
      out.write("\t\t$.fileDownload(\"");
      out.print(request.getContextPath());
      out.write("/pds/document/fileDownload\", {\r\n");
      out.write("\t\t\thttpMethod: \"POST\",\r\n");
      out.write("\t\t    data: file,\r\n");
      out.write("\t\t\tsuccessCallback: function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t   \t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tfailCallback: function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
