/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-07-09 05:06:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board.free;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class freeboardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/commons/pagination.jsp", Long.valueOf(1594192137156L));
    _jspx_dependants.put("/WEB-INF/views/board/free/freeboardList_js.jsp", Long.valueOf(1594192134639L));
    _jspx_dependants.put("/WEB-INF/views/board/free/mail_js.jsp", Long.valueOf(1594192134636L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\" />\r\n");
      out.write("\t<link rel='stylesheet' href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/professor/student.css\">\r\n");
      out.write("\t\r\n");
      out.write("<style>\r\n");
      out.write("table{\r\n");
      out.write("\t\tborder-collapse:separate ;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write(".container-dashboard {\r\n");
      out.write("    padding-top: 15px;\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".meminfo {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".popupLayer {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("\tborder: solid 2px #d0d0d0;\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\theight: 150px;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write(".popupLayer div {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 5px;\r\n");
      out.write("\tright: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#picturePreView{\r\n");
      out.write("\theight:100%;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tborder : 1px solid lightgray;  \t\t\r\n");
      out.write("\tbackground-position: center;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-size: 100% 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\t<!-- FAVIICON -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\t<!-- Le fav and touch icons -->\r\n");
      out.write("\t<link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"apple-touch-icon-114x114.png\" />\r\n");
      out.write("\t<link rel=\"icon\" type=\"images/svg+xml\" href=\"images/logo.svg\" />\r\n");
      out.write("<script>\r\n");
      out.write("\t\t$('.meminfo').each(function(){}).click(function(event) {\r\n");
      out.write("\t\t\tevent.preventDefault(); \r\n");
      out.write("\t\t\tconsol.log($('.meminfo'));\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("</script>\t\r\n");
      out.write("\r\n");
      out.write("<body class=\"blur-theme data-container-body\">\r\n");
      out.write("\t<div id=\"projectmaster\" class=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container-dashboard\">\r\n");
      out.write("\t\t\t\t<div class=\"container-dashboard-inner\">\r\n");
      out.write("\t\t\t\t\t<h3>커뮤니티  > 자유게시판</h3>\r\n");
      out.write("\t\t\t\t\t<form class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button id=\"writeBtn\" class=\"form-control\" type=\"button\" onclick=\"goSubmit('post','');\">작성</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-right\" id=\"keyword\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"searchType\" id=\"searchType\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"tcw\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 'tcw' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">전 체</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"t\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 't' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">제 목</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"w\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 'w' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">작성자</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"c\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 'c' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">내 용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"tc\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 'tc' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">제목+내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"cw\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 'cw' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">작성자+내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"검색어를 입력해주세요\" id=\"keyword\" name=\"keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.keyword }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-search search-box\" aria-hidden=\"true\" id=\"searchBtn\" style=\"cursor:pointer;\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-striped\" style=\"font-size: 1.4em;\">\r\n");
      out.write("\t\t\t\t\t\t<thead id=\"trtr\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"text-center\">번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"text-center\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"text-center\">작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"text-center\">날짜</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"text-center\">조회수</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/board/free/freeboardList.jsp(111,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/free/freeboardList.jsp(111,5) '${point}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${point}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/board/free/freeboardList.jsp(111,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("point");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td class=\"text-center\" style=\"color:red;\"><img src=\"");
            out.print(request.getContextPath() );
            out.write("/resources/images/important.png\"></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td class=\"text-center\" >\r\n");
            out.write("\t\t\t\t\t\t\t\t<a style=\"font-weight: bold; color: blue;\" href=\"");
            out.print(request.getContextPath() );
            out.write("/board/notice/detail?notice_no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point.notice_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point.notice_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td class=\"table-text-status\" align=\"center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<span class=\"issue-text\" ></span>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point.notice_writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td style=\"color:red;\" align=\"center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa\">");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return;
            out.write("</i></a>\r\n");
            out.write("\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td class=\"text-center\" style=\"color:red;\" align=\"center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"text-center\" aria-hidden=\"true\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point.notice_viewcnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</i></a>\r\n");
            out.write("\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      }
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/board/free/freeboardList.jsp(132,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/free/freeboardList.jsp(132,7) '${freeboardList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${freeboardList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/board/free/freeboardList.jsp(132,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("freeboard");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td class=\"text-center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboard.freeboard_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td class=\"text-center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<a href=\"");
            out.print(request.getContextPath());
            out.write("/board/free/detail?freeboard_no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboard.freeboard_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboard.freeboard_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return;
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td class=\"table-text-status\" align=\"center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            out.write("<a class=\"meminfo\" rel=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboard.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" href=\"#\" data-hasqtip=\"21\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"issue-text\" title=\"작성자\"></i>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboard.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa text-center\" aria-hidden=\"true\">");
            if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return;
            out.write("</i>\r\n");
            out.write("\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td align=\"center\" class=\"text-center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa text-center\" aria-hidden=\"true\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboard.freeboard_viewcnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</i>\r\n");
            out.write("\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      }
      out.write("</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"popupLayer\" id=\"meminfo\" style=\"z-index: 100\">\r\n");
      out.write("\t<div style=\"z-index: 100\">\r\n");
      out.write("\t\t<span onClick=\"closeLayer(this)\" style=\"cursor:pointer;font-size:1.5em\" title=\"닫기\">X</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("<table border=\"0\" style=\"font-size:9pt; width:100%; font-size: 1.4em;\" cellspacing=0 cellpadding=0>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<div id=\"picutreDiv\" role=\"picture\" align=\"left\" style=\"width: 100px; height: 120px;\">\r\n");
      out.write("\t\t\t<div id=\"picturePreView\"></div>\t\t\t\t\t\t \r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<td valign=\"center\">\r\n");
      out.write("\t\t\t<table id=Info border=0 cellpadding=0 cellspacing=0>\r\n");
      out.write("\t\t\t\t<tr height=22>\r\n");
      out.write("\t\t\t\t\t<td id=\"InfoMemtext\">&nbsp;<img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/info/etc_infor_dot.gif\" border=0>아이디 : </td>\r\n");
      out.write("\t\t\t\t\t<td id=\"InfoMemId\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr height=22>\r\n");
      out.write("\t\t\t\t\t<td id=\"InfoEmail\">&nbsp;<img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/info/etc_infor_dot.gif\" border=0>이메일 : </td>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<td id=\"InfoMemEmail\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"sendMail\" class=\"overlay light\" style=\"z-index: 100\">\r\n");
      out.write("\t\t<div class=\"popup2\">\r\n");
      out.write("\t\t\t<h4>■ 메일 전송  &nbsp;<button class=\"mailBtn\" id=\"mailCancel\">취소</button>\r\n");
      out.write("\t\t\t<button class=\"mailBtn\" id=\"sendBtn\">전송</button></h4>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label class=\"title-label\">제목</label><br/>\r\n");
      out.write("\t\t\t\t<input class=\"mail-title\" type=\"text\" id=\"title\" placeholder=\"제목을 입력해 주세요\">\r\n");
      out.write("\t\t\t\t<label class=\"content-label\">내용</label><br/>\r\n");
      out.write("\t\t\t\t<textarea id=\"mail-content\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<form id=\"jobForm\">\r\n");
      out.write("\t\t  <input type='hidden' name=\"page\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t  <input type='hidden' name=\"perPageNum\" \r\n");
      out.write("\t\t  \t\t value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.perPageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("\t\t  <input type='hidden' name=\"searchType\" \r\n");
      out.write("\t\t         value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t  <input type='hidden' name=\"keyword\" \r\n");
      out.write("\t\t         value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.keyword }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- include summernote css/js-->\r\n");
      out.write("<link href=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#mail-content').summernote({\r\n");
      out.write("\t\tplaceholder: '내용을 작성하세요.',\r\n");
      out.write("        tabsize: 1,\r\n");
      out.write("\t\theight: 200,\r\n");
      out.write("\t\tfontNames : [ '맑은고딕', 'Arial', 'Arial Black', 'Comic Sans MS', 'Courier New', ],\r\n");
      out.write("\t\tfontNamesIgnoreCheck : [ '맑은고딕' ],\r\n");
      out.write("\t\tfocus: true,\r\n");
      out.write("\t\ttoolbar: [\r\n");
      out.write("\t\t\t    // [groupName, [list of button]]\r\n");
      out.write("\t\t\t    ['style', ['bold', 'italic', 'underline', 'clear']],\r\n");
      out.write("\t\t\t    ['font', ['strikethrough', 'superscript', 'subscript']],\r\n");
      out.write("\t\t\t    ['fontsize', ['fontsize']],\r\n");
      out.write("\t\t\t    ['color', ['color']],\r\n");
      out.write("\t\t\t  ]\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("})\r\n");
      out.write("</script>");
      out.write("<script>\r\n");
      out.write("$('#searchBtn').on('click',function(e){\r\n");
      out.write("\t\r\n");
      out.write("\tvar jobForm=$('#jobForm');\r\n");
      out.write("\tjobForm.find(\"[name='page']\").val(1);\r\n");
      out.write("\tjobForm.find(\"[name='searchType']\").val($('select[name=\"searchType\"]').val());\r\n");
      out.write("\tjobForm.find(\"[name='keyword']\").val($('input[name=\"keyword\"]').val());\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tjobForm.attr(\"action\",\"free.do\").attr(\"method\",\"get\");\r\n");
      out.write("\tjobForm.submit(); \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function searchList_go(page,url){\r\n");
      out.write("\t\r\n");
      out.write("\tvar jobForm=$('#jobForm');\r\n");
      out.write("\tjobForm.find(\"[name='page']\").val(page);\r\n");
      out.write("\tjobForm.find(\"[name='searchType']\").val($('select[name=\"searchType\"]').val());\r\n");
      out.write("\tjobForm.find(\"[name='keyword']\").val($('div.input-group>input[name=\"keyword\"]').val());\r\n");
      out.write("\tjobForm.attr(\"method\",\"post\");\r\n");
      out.write("\tif(url){\r\n");
      out.write("\t\tjobForm.attr(\"action\",url)\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tjobForm.attr(\"action\",\"free.do\")\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tjobForm.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*아이디 클릭시 팝업 생성*/\r\n");
      out.write("function closeLayer( obj ) {\r\n");
      out.write("\t\t$(obj).parent().parent().hide();\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\r\n");
      out.write("\t/* 클릭 클릭시 클릭을 클릭한 위치 근처에 레이어가 나타난다. */\r\n");
      out.write("\t$('.meminfo').click(function(e){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar sWidth = window.innerWidth;\r\n");
      out.write("\t\tvar sHeight = window.innerHeight;\r\n");
      out.write("\r\n");
      out.write("\t\tvar oWidth = $('.popupLayer').width();\r\n");
      out.write("\t\tvar oHeight = $('.popupLayer').height();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 레이어가 나타날 위치를 셋팅한다.\r\n");
      out.write("\t\tvar divLeft = e.clientX + 10;\r\n");
      out.write("\t\tvar divTop = e.clientY + 5;\r\n");
      out.write("\r\n");
      out.write("\t\t// 레이어가 화면 크기를 벗어나면 위치를 바꾸어 배치한다.\r\n");
      out.write("\t\tif( divLeft + oWidth > sWidth ) divLeft -= oWidth;\r\n");
      out.write("\t\tif( divTop + oHeight > sHeight ) divTop -= oHeight;\r\n");
      out.write("\r\n");
      out.write("\t\t// 레이어 위치를 바꾸었더니 상단기준점(0,0) 밖으로 벗어난다면 상단기준점(0,0)에 배치한다\r\n");
      out.write("\t\tif( divLeft < 0 ) divLeft = 0;\r\n");
      out.write("\t\tif( divTop < 0 ) divTop = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.popupLayer').css({\r\n");
      out.write("\t\t\t\"top\": divTop,\r\n");
      out.write("\t\t\t\"left\": divLeft,\r\n");
      out.write("\t\t\t\"position\": \"absolute\"\r\n");
      out.write("\t\t}).show();\r\n");
      out.write("\t\tvar memId = $(this).attr(\"rel\");\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"get\",\r\n");
      out.write(" \t\t\tdata:{\r\n");
      out.write(" \t\t\t\t//member_id:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'\r\n");
      out.write(" \t\t\t\tmember_id:memId,\r\n");
      out.write(" \t\t\t},\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/board/free/memInfo/\" + memId,\r\n");
      out.write("\t\t\tsuccess:function(suc){\r\n");
      out.write("\t\t\t\tconsole.log(suc);\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\tif(suc.infoOpen == \"Y\"){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#InfoMemId\").empty();\r\n");
      out.write("\t\t\t\t$(\"#InfoMemId\").append( suc.id);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#InfoMemEmail\").empty();\r\n");
      out.write("\t\t\t\t$(\"#InfoMemEmail\").html(\"<a href='#sendMail' class='infoEmail'>\"+suc.email+\"</a>\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#picturePreView\").empty();\r\n");
      out.write("\t\t\t\t$(\"#picturePreView\").css(\"background-image\",\"url('");
      out.print(request.getContextPath());
      out.write("/board/free/picture/\" + suc.id + \"')\" );\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t$(\"#InfoMemId\").empty();\r\n");
      out.write("\t\t\t\t\t$(\"#InfoMemId\").append( \"비공개\");\r\n");
      out.write("\t\t\t\t\t$(\"#InfoMemEmail\").empty();\r\n");
      out.write("\t\t\t\t\t$(\"#InfoMemEmail\").append(\"비공개\");\r\n");
      out.write("\t\t\t\t\t$(\"#picturePreView\").empty();\r\n");
      out.write("\t\t\t\t\t$(\"#picturePreView\").css(\"background-image\",\"url('");
      out.print(request.getContextPath());
      out.write("/resources/images/info/사용자.png')\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* $(\"#InfoMemId\").remove();\r\n");
      out.write("\t\t\t\t$(\"#InfoMemEmail\").remove();\r\n");
      out.write("\t\t\t\t$(\"#picturePreView\").remove();\r\n");
      out.write("\t\t\t\t */\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(err){\r\n");
      out.write("\t\t\t\talert(\"에러\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"json\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("/*이메일*/\r\n");
      out.write("\r\n");
      out.write("\t$('.popupLayer').on('click','.infoEmail',function(){\r\n");
      out.write("\t\tvar id = $('#InfoMemEmail').text(); \r\n");
      out.write("\t});\r\n");
      out.write("\t/* function sendMailForm(id){\r\n");
      out.write("\t\t$('#InfoMemId').val(id);\r\n");
      out.write("\t} \r\n");
      out.write("\t */\r\n");
      out.write("\t$('#mailCancel').on('click',function(){\r\n");
      out.write("\t\tvar id = $('#InfoMemId').text(); \r\n");
      out.write(" \t\tlocation.href=\"#meminfo\";\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('#sendBtn').on('click',function(){\r\n");
      out.write("\r\n");
      out.write("\t\tvar id = $('#InfoMemId').text();\r\n");
      out.write("\t\tvar title = $('#title').val();\r\n");
      out.write("\t\tvar content = $('#mail-content').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/board/free/infoMail\",\r\n");
      out.write("\t\t\tdata:{\"id\": id,\"title\":title,\"content\":content},\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert('메일을 성공적으로 보냈습니다.')\r\n");
      out.write("\t\t\t\tlocation.href=\"#meminfo\";\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(exception){\r\n");
      out.write("\t\t\t\talert(exception);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write(" <nav aria-label=\"member list Navigation\" class=\"paginationNav text-center\">\r\n");
      out.write("\t<ul class=\"pagination justify-content-center m-0\">\r\n");
      out.write("\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t<a class=\"page-link\" href=\"javascript:searchList_go(1);\">\r\n");
      out.write("\t\t\t<i class=\"glyphicon glyphicon-step-backward\"></i>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t<a class=\"page-link\" href=\"javascript:searchList_go(\r\n");
      out.write("\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.prev ? pageMaker.startPage-1 : 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t);\"><i class=\"glyphicon glyphicon-chevron-left\"></i></a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("<li class=\"page-item\">\r\n");
      out.write("\t\t\t<a class=\"page-link\" href=\"javascript:searchList_go(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.next ? pageMaker.endPage+1 : pageMaker.cri.page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(");\"><i class=\"glyphicon glyphicon-chevron-right\" ></i></a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t<a class=\"page-link\" href=\"javascript:searchList_go(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.realEndPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(");\">\r\n");
      out.write("\t\t\t\t<i class=\"glyphicon glyphicon-step-forward\"></i></a>\r\n");
      out.write("\t\t</li>\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("</nav>   \t");
      out.write("<!-- include summernote css/js-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("/**\r\n");
      out.write(" * 작성 버튼 클릭시 화면 전환\r\n");
      out.write(" */\r\n");
      out.write(" function goSubmit(){ \r\n");
      out.write("\t if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" == \"\"){\r\n");
      out.write("\t\t\talert(\"로그인 후 작성 가능합니다.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/board/free/regist\";\r\n");
      out.write("\t}\r\n");
      out.write(" \r\n");
      out.write(" /*\r\n");
      out.write(" \tdetail화면 전환\r\n");
      out.write(" */\r\n");
      out.write(" function doDetail(){\r\n");
      out.write("\t alert(\"클릭\");\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" function OpenWindow(UrlStr, WinTitle, WinWidth,WinHeight) {\r\n");
      out.write("\t\twinleft = (screen.width - WinWidth) / 2;\r\n");
      out.write("\t\twintop = (screen.height - WinHeight) / 2;\r\n");
      out.write("\t\tvar win = window.open(UrlStr, WinTitle, \"scrollbars=yes, width=\"+ WinWidth + \",\" \r\n");
      out.write("\t\t\t\t\t\t+ \"height=\" + WinHeight + \", top=\" + wintop + \", left=\"\r\n");
      out.write("\t\t\t\t\t\t+ winleft + \",resizable=yes, status=yes\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\twin.focus();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" /*검색 기능*/\r\n");
      out.write("\r\n");
      out.write(" $('#searchBtn').on('click',function(e){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar jobForm=$('#jobForm');\r\n");
      out.write("\t\tjobForm.find(\"[name='page']\").val(1);\r\n");
      out.write("\t\tjobForm.find(\"[name='searchType']\").val($('select[name=\"searchType\"]').val());\r\n");
      out.write("\t\tjobForm.find(\"[name='keyword']\").val($('input[name=\"keyword\"]').val());\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tjobForm.attr(\"action\",\"free.do\").attr(\"method\",\"get\");\r\n");
      out.write("\t\tjobForm.submit(); \r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/board/free/freeboardList.jsp(124,35) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point.notice_regdate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /WEB-INF/views/board/free/freeboardList.jsp(124,35) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
    int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /WEB-INF/views/board/free/freeboardList.jsp(137,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboard.freeReplycnt > 0 }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<span style=\"color:blue;font-weight:bold;\"> [");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboard.freeReplycnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("]</span> ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /WEB-INF/views/board/free/freeboardList.jsp(152,54) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboard.freeboard_regdate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /WEB-INF/views/board/free/freeboardList.jsp(152,54) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f1.setPattern("yyyy-MM-dd");
    int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /WEB-INF/views/commons/pagination.jsp(17,2) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setBegin(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.startPage }", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).intValue());
    // /WEB-INF/views/commons/pagination.jsp(17,2) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.endPage }", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).intValue());
    // /WEB-INF/views/commons/pagination.jsp(17,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("pageNum");
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<li class=\"page-item \r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
            return true;
          out.write("\">\r\n");
          out.write("\t\t\t<a class=\"page-link\" href=\"javascript:searchList_go(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(");\" >");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a>\r\n");
          out.write("\t\t</li>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
    // /WEB-INF/views/commons/pagination.jsp(19,3) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.page == pageNum?'active':''}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
