/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-07-09 02:46:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board.foundedReview;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class foundReviewList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/commons/pagination.jsp", Long.valueOf(1594192137156L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/slider/sliderDisplay.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/slider/sliderOption.css\" />\r\n");
      out.write(" <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/slider/jquery.slides.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\t.tableIntheText{\r\n");
      out.write("\t\tfont-size: 1.4em;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.tableIntheText a{\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.tableIntheText a:hover{\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tcolor: #ff434396;\r\n");
      out.write("\t}\r\n");
      out.write("/* \t.tableIntheText:hover{\r\n");
      out.write("\t\tbackground: #afffaf3b;\r\n");
      out.write("\t}\r\n");
      out.write(" */\t.thText{\r\n");
      out.write("\t\tfont-size: 1.6em;\r\n");
      out.write("\t}\r\n");
      out.write("\t.imageReview{\r\n");
      out.write("\t\twidth: 437px;\r\n");
      out.write("\t    height: 224px;\r\n");
      out.write("\t    float: left;\r\n");
      out.write("\t    margin-left: 133px;\r\n");
      out.write("\t    padding-right: 163px;\r\n");
      out.write("\t    border-right: 4px ridge;\r\n");
      out.write("\t}\r\n");
      out.write("\t.contentText{\r\n");
      out.write("\t\toverflow: auto;\r\n");
      out.write("   \t\tpadding: 0px 30px;\r\n");
      out.write("   \t\twidth: 50%;\r\n");
      out.write("   \t\theight: 239px;\r\n");
      out.write("\t}\r\n");
      out.write("\t::-webkit-scrollbar{width: 16px;}\r\n");
      out.write("\t::-webkit-scrollbar-track{background-color: #f7ffe9;}\r\n");
      out.write("\t::-webkit-scrollbar-thumb{background-color: #555; border-radius: 10px;}\r\n");
      out.write("\t::-webkit-scrollbar-button:start:decrement, ::webkit-scrollber-button:end:increment{width: 16px;height: 16px;background: #f1ef79;}\r\n");
      out.write("\t\r\n");
      out.write("\t.ReviewWrap{\r\n");
      out.write("\t\tmargin-top: 20px;\r\n");
      out.write("\t\tbackground: #f7ffe9;\r\n");
      out.write("\t}\r\n");
      out.write("\t.noticeTr{\r\n");
      out.write("\t\tbackground: orange;\r\n");
      out.write("\t}\r\n");
      out.write("\t.noticeTr td img{\r\n");
      out.write("\t\twidth: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.slidesjs-previous{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t    top: 339px;\r\n");
      out.write("\t    z-index: 20;\r\n");
      out.write("\t    \r\n");
      out.write("\t}\r\n");
      out.write("\t.slidesjs-next{\r\n");
      out.write("\t    position: absolute;\r\n");
      out.write("\t    top: 338px;\r\n");
      out.write("\t    right: 294px;\r\n");
      out.write("\t    z-index: 20;\r\n");
      out.write("\t}\r\n");
      out.write("\t.imageReview img {\r\n");
      out.write("\t\twidth: 114%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.review_title{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.tooltipbox {\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\tbackground: #208dd5;\r\n");
      out.write("\t\tborder: 4px solid #d3f4f5;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tooltipbox:after, .tooltipbox:before {\r\n");
      out.write("\t\tright: 100%;\r\n");
      out.write("\t\ttop: 50%;\r\n");
      out.write("\t\tborder: solid transparent;\r\n");
      out.write("\t\tcontent: \" \";\r\n");
      out.write("\t\theight: 0;\r\n");
      out.write("\t\twidth: 0;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tpointer-events: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.tooltipbox:after {\r\n");
      out.write("\t\tborder-color: rgba(32, 141, 213, 0);\r\n");
      out.write("\t\tborder-right-color: #208dd5;\r\n");
      out.write("\t\tborder-width: 52px;\r\n");
      out.write("\t\tmargin-top: -52px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tooltipbox:before {\r\n");
      out.write("\t\tborder-color: rgba(211, 244, 245, 0);\r\n");
      out.write("\t\tborder-right-color: #d3f4f5;\r\n");
      out.write("\t\tborder-width: 58px;\r\n");
      out.write("\t\tmargin-top: -58px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.h3Title{\r\n");
      out.write("\t\tpadding-left: 24px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.hrLine{\r\n");
      out.write("\t\tmargin-left: 24px;\r\n");
      out.write("\t    margin-right: 24px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.worText{\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\tcolor: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t.notLoginUserworText,.notAttendStatusText{\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\tcolor: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t#slides img{\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body class=\"blur-theme data-container-body\">\r\n");
      out.write("\t<div class=\"wrapBody\">\r\n");
      out.write("\t\t<div class=\"ReviewWrap\">\r\n");
      out.write("\t\t  <div id=\"slides\">\r\n");
      out.write("\t\t\t<div class=\"ReviewTtitle\">\r\n");
      out.write("\t\t\t\t<h3 class=\"h3Title\">베스트 창업  후기</h3>\r\n");
      out.write("\t\t\t\t<hr class=\"hrLine\">\r\n");
      out.write("\t\t\t\t<div class=\"imageReview bestImage1\" onclick=\"ImageClickdetail(this)\">\r\n");
      out.write("\t\t\t\t\t<img src=\"#\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" class=\"image1\"> \r\n");
      out.write("\t\t\t\t<div class=\"contentText contentText1 scrollbars\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"ReviewTtitle \">\r\n");
      out.write("\t\t\t\t<h3 class=\"h3Title\">베스트 창업  후기</h3>\r\n");
      out.write("\t\t\t\t<hr class=\"hrLine\">\r\n");
      out.write("\t\t\t\t<div class=\"imageReview bestImage2\"  onclick=\"ImageClickdetail(this)\">\r\n");
      out.write("\t\t\t\t\t<img src=\"#\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" class=\"image2\">\r\n");
      out.write("\t\t\t\t<div class=\"contentText contentText2 scrollbars\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"ReviewTtitle \">\r\n");
      out.write("\t\t\t\t<h3 class=\"h3Title\">베스트 창업  후기</h3>\r\n");
      out.write("\t\t\t\t<hr class=\"hrLine\">\r\n");
      out.write("\t\t\t\t<div class=\"imageReview bestImage3\"  onclick=\"ImageClickdetail(this)\">\r\n");
      out.write("\t\t\t\t\t<img src=\"#\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" class=\"image3\">\r\n");
      out.write("\t\t\t\t<div class=\"contentText contentText3 scrollbars\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"ReviewTtitle \">\r\n");
      out.write("\t\t\t\t<h3 class=\"h3Title\">베스트 창업  후기</h3>\r\n");
      out.write("\t\t\t\t<hr class=\"hrLine\">\r\n");
      out.write("\t\t\t\t<div class=\"imageReview bestImage4\"  onclick=\"ImageClickdetail(this)\">\r\n");
      out.write("\t\t\t\t\t<img src=\"#\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" class=\"image4\">\r\n");
      out.write("\t\t\t\t<div class=\"contentText contentText4 scrollbars\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"ReviewTtitle \">\r\n");
      out.write("\t\t\t\t<h3 class=\"h3Title\">베스트 창업  후기</h3>\r\n");
      out.write("\t\t\t\t<hr class=\"hrLine\">\r\n");
      out.write("\t\t\t\t<div class=\"imageReview bestImage5\"  onclick=\"ImageClickdetail(this)\">\r\n");
      out.write("\t\t\t\t\t<img src=\"#\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" class=\"image5\">\r\n");
      out.write("\t\t\t\t<div class=\"contentText contentText5 scrollbars\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"projectmaster\" class=\"content\">\r\n");
      out.write("\t\t\t<div class=\"menu-search-block\">\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t<div class=\"pull-left foundedListTitle\">\r\n");
      out.write("\t\t\t\t\t\t<h3>창업 후기</h3>\r\n");
      out.write("\t\t\t\t\t\t<span>전체 게시글 수: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.totalCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" 건</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"container-dashboard\">\r\n");
      out.write("\t\t\t\t<div class=\"container-dashboard-inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pull-left\" id=\"keyword\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"searchType\" id=\"searchType\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"tcw\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 'tcw' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">전 체</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"t\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 't' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">제 목</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"w\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 'w' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">작성자</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"c\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 'c' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">내 용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"tc\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 'tc' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">제목+내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"cw\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType eq 'cw' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">작성자+내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"검색어를 입력해주세요\" id=\"keyword\" name=\"keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.keyword }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-search search-box fa-2x\" aria-hidden=\"true\" id=\"searchBtn\" style=\"cursor:pointer;\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pull-right\" id=\"regist\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"worText\">수강생만 등록 가능합니다.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"notLoginUserworText\">로그인 후 사용 가능합니다.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"notAttendStatusText\">수강수료 후 작성 가능합니다.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-primary\"  onclick=\"foundedWrite();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"\"></i><b>작성</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"thText\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">날짜</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">조회수</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t ");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/board/foundedReview/foundReviewList.jsp(231,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/foundedReview/foundReviewList.jsp(231,9) '${pointList }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pointList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/board/foundedReview/foundReviewList.jsp(231,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("noticePoint");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<tr class=\"noticeTr\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"text-center\" style=\"color:red;\"><img src=\"");
            out.print(request.getContextPath() );
            out.write("/resources/images/pointImg.png\"></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"text-center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<a style=\"font-weight: bold; color: blue;\" href=\"");
            out.print(request.getContextPath() );
            out.write("/board/notice/detail?notice_no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noticePoint.notice_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noticePoint.notice_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"text-center table-text-status\" >\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"issue-text\"></span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noticePoint.notice_writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"text-center\"  style=\"color:red;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-calendar\" aria-hidden=\"true\"></i>&nbsp;");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"text-center\" style=\"color:red;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"text-center\" aria-hidden=\"true\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noticePoint.notice_viewcnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</i></a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      }
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"paginationWrap\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write(" <nav aria-label=\"member list Navigation\" class=\"paginationNav text-center\">\r\n");
      out.write("\t<ul class=\"pagination justify-content-center m-0\">\r\n");
      out.write("\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t<a class=\"page-link\" href=\"javascript:searchList_go(1);\">\r\n");
      out.write("\t\t\t<i class=\"glyphicon glyphicon-step-backward\"></i>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t<a class=\"page-link\" href=\"javascript:searchList_go(\r\n");
      out.write("\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.prev ? pageMaker.startPage-1 : 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t);\"><i class=\"glyphicon glyphicon-chevron-left\"></i></a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("<li class=\"page-item\">\r\n");
      out.write("\t\t\t<a class=\"page-link\" href=\"javascript:searchList_go(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.next ? pageMaker.endPage+1 : pageMaker.cri.page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(");\"><i class=\"glyphicon glyphicon-chevron-right\" ></i></a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t<a class=\"page-link\" href=\"javascript:searchList_go(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.realEndPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(");\">\r\n");
      out.write("\t\t\t\t<i class=\"glyphicon glyphicon-step-forward\"></i></a>\r\n");
      out.write("\t\t</li>\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("</nav>   \t");
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<form id=\"searchForm\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type='hidden' name=\"page\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input type='hidden' name=\"perPageNum\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.perPageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type='hidden' name=\"searchType\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.searchType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input type='hidden' name=\"keyword\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.keyword }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".foundedListTitle\").val();\r\n");
      out.write("\r\n");
      out.write("$(function () {\r\n");
      out.write("\t  $('[data-toggle=\"tooltip\"]').tooltip()\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("//메인화면  이미지 슬라이드 작업\r\n");
      out.write("//https://slidesjs.com  옵션 기능 추가시 참조  \r\n");
      out.write("$(function() {\r\n");
      out.write("  $('#slides').slidesjs({\r\n");
      out.write("    width: 700,\r\n");
      out.write("    height: 200\r\n");
      out.write("    /* play: {\r\n");
      out.write("      active: true,\r\n");
      out.write("      auto: true,\r\n");
      out.write("      interval: 4000,\r\n");
      out.write("      swap: true\r\n");
      out.write("    } */\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function openTheProfile(obj){\r\n");
      out.write("\t\r\n");
      out.write("\tvar writter =$(obj).text();\r\n");
      out.write("\r\n");
      out.write("\tvar data ={\"writter\" : writter}\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/board/foundedReview/profile?writter=\"+writter,\r\n");
      out.write("\t\ttype:\"post\",\r\n");
      out.write("\t\tdata:JSON.stringify(data),\r\n");
      out.write("\t\tsuccess:function(suc){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(err){\r\n");
      out.write("\t\t\talert(\"실패\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//창업후기 작성 버튼\r\n");
      out.write("function foundedWrite(){\r\n");
      out.write("\t\r\n");
      out.write("\t//수강생만 작성가능 기능\r\n");
      out.write("\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_authority}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" == \"PROFESSOR\" || \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_authority}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" == \"ADMIN\" ){\r\n");
      out.write("\t\t$(\".worText\").show();\r\n");
      out.write("\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t$(\".worText\").hide();\r\n");
      out.write("\t\t},1000)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//로그인상태 여부 확인\r\n");
      out.write("\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" == \"\"){\r\n");
      out.write("\t\t$(\".notLoginUserworText\").show();\r\n");
      out.write("\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t$(\".notLoginUserworText\").hide();\r\n");
      out.write("\t\t},1000)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//출석률 80%이상일때 창업후기 작성 가능\r\n");
      out.write("\r\n");
      out.write("\tlocation.href='");
      out.print(request.getContextPath() );
      out.write("/board/foundedReview/registForm'\r\n");
      out.write("\t\t\t \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("$('#searchBtn').on('click',function(e){\r\n");
      out.write("\tif($(\"#keyword\").val() ==\"\"){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar searchForm=$('#searchForm');\r\n");
      out.write("\tsearchForm.find(\"[name='page']\").val(1);\r\n");
      out.write("\tsearchForm.find(\"[name='searchType']\").val($('select[name=\"searchType\"]').val());\r\n");
      out.write("\tsearchForm.find(\"[name='keyword']\").val($('input[name=\"keyword\"]').val());\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tsearchForm.attr(\"action\",\"foundReviewList\").attr(\"method\",\"get\");\r\n");
      out.write("\tsearchForm.submit(); \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function searchList_go(page){\r\n");
      out.write("\t\r\n");
      out.write("\tvar searchForm=$('#searchForm');\r\n");
      out.write("\tsearchForm.find(\"[name='page']\").val(page);\r\n");
      out.write("\tsearchForm.find(\"[name='searchType']\").val($('select[name=\"searchType\"]').val());\r\n");
      out.write("\tsearchForm.find(\"[name='keyword']\").val($('input[name=\"keyword\"]').val());\r\n");
      out.write("\tsearchForm.attr(\"action\",\"foundReviewList\").attr(\"method\",\"get\");\r\n");
      out.write("\t\r\n");
      out.write("\tsearchForm.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" $.ajax({\r\n");
      out.write("\turl:\"");
      out.print(request.getContextPath());
      out.write("/board/foundedReview/bestFoundedReview\",\r\n");
      out.write("\ttype: \"get\",\r\n");
      out.write("\tsuccess:function(suc){\r\n");
      out.write("\t\tconsole.log(suc);\r\n");
      out.write("\t\tvar imgeName1=suc.foundedImgList0[0].founded_review_img_name;\r\n");
      out.write(" \t\tvar imgeName2=suc.foundedImgList1[0].founded_review_img_name;\r\n");
      out.write("\t\tvar imgeName3=suc.foundedImgList2[0].founded_review_img_name;\r\n");
      out.write("\t\tvar imgeName4=suc.foundedImgList3[0].founded_review_img_name;\r\n");
      out.write("\t\tvar imgeName5=suc.foundedImgList4[0].founded_review_img_name; \r\n");
      out.write("\t\t$(\".contentText1\").append(\"<p class='review_title'>\"+suc.foundedList[0].founded_review_title+\"</p>\")\r\n");
      out.write("\t\t$(\".contentText1\").append(suc.foundedList[0].founded_review_content);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".contentText2\").append(\"<p class='review_title'>\"+suc.foundedList[1].founded_review_title+\"</p>\")\r\n");
      out.write("\t\t$(\".contentText2\").append(suc.foundedList[1].founded_review_content);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".contentText3\").append(\"<p class='review_title'>\"+suc.foundedList[2].founded_review_title+\"</p>\")\r\n");
      out.write("\t\t$(\".contentText3\").append(suc.foundedList[2].founded_review_content);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".contentText4\").append(\"<p class='review_title'>\"+suc.foundedList[3].founded_review_title+\"</p>\")\r\n");
      out.write("\t\t$(\".contentText4\").append(suc.foundedList[3].founded_review_content);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".contentText5\").append(\"<p class='review_title'>\"+suc.foundedList[4].founded_review_title+\"</p>\")\r\n");
      out.write("\t\t$(\".contentText5\").append(suc.foundedList[4].founded_review_content);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".bestImage1 img\").attr(\"src\",\"");
      out.print(request.getContextPath());
      out.write("/board/foundedImge?fileName=\"+imgeName1)\r\n");
      out.write(" \t\t$(\".bestImage2 img\").attr(\"src\",\"");
      out.print(request.getContextPath());
      out.write("/board/foundedImge?fileName=\"+imgeName2)\r\n");
      out.write("\t\t$(\".bestImage3 img\").attr(\"src\",\"");
      out.print(request.getContextPath());
      out.write("/board/foundedImge?fileName=\"+imgeName3)\r\n");
      out.write("\t\t$(\".bestImage4 img\").attr(\"src\",\"");
      out.print(request.getContextPath());
      out.write("/board/foundedImge?fileName=\"+imgeName4)\r\n");
      out.write("\t\t$(\".bestImage5 img\").attr(\"src\",\"");
      out.print(request.getContextPath());
      out.write("/board/foundedImge?fileName=\"+imgeName5)\r\n");
      out.write("\t\t$(\"input.image1\").val(suc.foundedImgList0[0].founded_review_no);\r\n");
      out.write("\t\t$(\".image2\").val(suc.foundedImgList1[0].founded_review_no);\r\n");
      out.write("\t\t$(\".image3\").val(suc.foundedImgList2[0].founded_review_no);\r\n");
      out.write("\t\t$(\".image4\").val(suc.foundedImgList3[0].founded_review_no);\r\n");
      out.write("\t\t$(\".image5\").val(suc.foundedImgList4[0].founded_review_no);\r\n");
      out.write("\t},\r\n");
      out.write("\terror:function(err){\r\n");
      out.write("\t\talert(\"에러\");\r\n");
      out.write("\t}\r\n");
      out.write(" })\r\n");
      out.write(" \r\n");
      out.write(" function ImageClickdetail(obj){\r\n");
      out.write("\t \t\r\n");
      out.write("\t var detailNum=$(obj).next().val();\r\n");
      out.write("\t\t \tlocation.href=\"/board/foundedReview/detail?founded_review_no=\"+detailNum; \r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/board/foundedReview/foundReviewList.jsp(241,66) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noticePoint.notice_regdate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /WEB-INF/views/board/foundedReview/foundReviewList.jsp(241,66) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
    int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/views/board/foundedReview/foundReviewList.jsp(248,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/foundedReview/foundReviewList.jsp(248,8) '${foundedList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${foundedList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/board/foundedReview/foundReviewList.jsp(248,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("foundedList");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<tr class=\"tableIntheText\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"text-center\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${foundedList.founded_review_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"text-center\"><a href=\"/board/foundedReview/detail?founded_review_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${foundedList.founded_review_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${foundedList.founded_review_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"text-center\"><p class=\"profileTooltip\" onclick=\"openTheProfile(this);\" >");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${foundedList.founded_review_writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</p></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"text-center\"><i class=\"fa fa-calendar\" aria-hidden=\"true\">&nbsp;</i>");
          if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"text-center\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${foundedList.founded_review_viewcnt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /WEB-INF/views/board/foundedReview/foundReviewList.jsp(253,89) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${foundedList.founded_review_regdate }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /WEB-INF/views/board/foundedReview/foundReviewList.jsp(253,89) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f1.setPattern("yyyy-MM-dd");
    int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /WEB-INF/views/commons/pagination.jsp(17,2) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setBegin(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.startPage }", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).intValue());
    // /WEB-INF/views/commons/pagination.jsp(17,2) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.endPage }", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).intValue());
    // /WEB-INF/views/commons/pagination.jsp(17,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("pageNum");
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<li class=\"page-item \r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
            return true;
          out.write("\">\r\n");
          out.write("\t\t\t<a class=\"page-link\" href=\"javascript:searchList_go(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(");\" >");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a>\r\n");
          out.write("\t\t</li>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
    // /WEB-INF/views/commons/pagination.jsp(19,3) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.cri.page == pageNum?'active':''}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
