/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-07-09 06:36:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.manager.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;

public final class managerNoticeRegist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/manager/notice/noticeRegist_js.jsp", Long.valueOf(1594192136389L));
    _jspx_dependants.put("/WEB-INF/views/manager/notice/noticeAttach_js.jsp", Long.valueOf(1594192136391L));
    _jspx_dependants.put("/WEB-INF/views/summernote_js.jsp", Long.valueOf(1594192138446L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<style>\r\n");
      out.write("@font-face {\r\n");
      out.write("  font-family: 'azo_sansbold';\r\n");
      out.write("  src: url('https://s3-us-west-2.amazonaws.com/s.cdpn.io/260783/rui_abreu_-_azosans-bold-webfont.eot');\r\n");
      out.write("  src: url('https://s3-us-west-2.amazonaws.com/s.cdpn.io/260783/rui_abreu_-_azosans-bold-webfont.eot?#iefix') format('embedded-opentype'), url('https://s3-us-west-2.amazonaws.com/s.cdpn.io/260783/rui_abreu_-_azosans-bold-webfont.woff2') format('woff2'), url('https://s3-us-west-2.amazonaws.com/s.cdpn.io/260783/rui_abreu_-_azosans-bold-webfont.woff') format('woff'), url('https://s3-us-west-2.amazonaws.com/s.cdpn.io/260783/rui_abreu_-_azosans-bold-webfont.woff') format('truetype'), url('https://s3-us-west-2.amazonaws.com/s.cdpn.io/260783/rui_abreu_-_azosans-bold-webfont.svg#azo_sansbold') format('svg');\r\n");
      out.write("  font-weight: normal;\r\n");
      out.write("  font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inner {\r\n");
      out.write("  \r\n");
      out.write("    background-color: white;\r\n");
      out.write("}\r\n");
      out.write("section#main-container {\r\n");
      out.write("    background-color: white;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".note-editor.note-frame {\r\n");
      out.write("    border: 1px solid #a9a9a9;\r\n");
      out.write("    width: 89.5%;\r\n");
      out.write("    float: right;\r\n");
      out.write("    height: 302px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#notice_regist:hover {\r\n");
      out.write("\tbackground: #C7C4FF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#notice_char:hover{\r\n");
      out.write("\tbackground: #C7C4FF;\r\n");
      out.write("}\r\n");
      out.write(".buttons{\r\n");
      out.write("\twidth:90px;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <div ng-controller=\"FormController\" >\r\n");
      out.write("        <form enctype=\"multipart/form-data\" name=\"regist\" method=\"post\" action=\"regist\" style=\"font-size: 20px;    margin-top: -35px;\" >\r\n");
      out.write("    \t  <section id=\"section-timesheet\" ng-class=\"{ scale: success }\">\r\n");
      out.write("    \t  \t<div class=\"inner\" style=\"width: 100%;\">\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write(" \t\t\t  <div id=\"notice_div\" >\r\n");
      out.write(" \t\t\t    <button id=\"notice_regist\" class=\"btn btn-block buttons\" type=\"button\" style=\"border-color: #C7C4FF;\">등록</button>\r\n");
      out.write("\t            <button id=\"notice_char\" class=\"btn btn-block buttons\" type=\"button\" style=\"border-color: #C7C4FF;\">목록</button>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t\t\t\t          \r\n");
      out.write("\t\t\t\t          \r\n");
      out.write("\t\t\t\t          \r\n");
      out.write("        <div style=\"height:30px; width: 100%;float: left; margin-bottom: 5px;margin-top: 5px;\">\r\n");
      out.write("\t  \t    \r\n");
      out.write("\t  \t     <div style=\"width: 34%;height: 100%;float:left;\" >\r\n");
      out.write("\t        \t <label style=\" background-color:#D6C7ED;height:100%; width: 114px;border-radius: 3px;text-align: center; padding-top:3px; float: left; \">구분</label>\r\n");
      out.write("\t\t\t\t <select class=\"\" name=\"notice_point\" id=\"notice_point\" style=\"height:100%;float:left;margin-left: 5px;width: 68%;text-align: \">\r\n");
      out.write("\t\t\t\t\t<option value=\"nomal\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.notice_point eq 'nomal' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">공지사항 일반글</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"notice\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.notice_point eq '\"notice\"' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">공지사항 중요글</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"free\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.notice_point eq 'free' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">자유게시판 중요글</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"lacture\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.notice_point eq 'lacture' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">수강후기 중요글</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Faunded\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.notice_point eq 'Faunded' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">창업후기 중요글</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"consult\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.notice_point eq 'consult' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">상담문의 중요글</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Q&A\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.notice_point eq 'Q&A' ? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">Q&A 중요글</option> \r\n");
      out.write("\t\t\t\t </select>\r\n");
      out.write("\t\t\t </div> \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t <div style=\"width: 33%;height: 100%;float:left;\" >\r\n");
      out.write("\t        \t <label style=\" background-color:#D6C7ED;height:100%; width: 114px;border-radius: 3px;text-align: center; padding-top:3px; float: left; \">마감일</label>\r\n");
      out.write("\t\t\t\t <input id=\"notice_finishdate\" name=\"notice_finishdate\" value=\"\" type=\"date\" style=\"width: 67%;height: 100%;margin-left: 5px;\">\r\n");
      out.write("\t\t\t </div> \t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t <div style=\"width: 33%;height: 100%;float:left;\" >\r\n");
      out.write("\t        \t <label style=\" background-color:#D6C7ED;height:100%; width: 114px;border-radius: 3px;text-align: center;padding-top:3px;float: left;\">작성자</label>\r\n");
      out.write("\t  \t    \t <input id=\"notice_writer\" name=\"notice_writer\" type=\"text\" value=\"admin\" required readonly=\"readonly\" style=\"height:100%;width:68%; margin-left: 5px;float: left;\">\r\n");
      out.write("  \t         </div> \r\n");
      out.write("  \t         \r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("  \t      \t<div style=\"width: 100%;height: 30px;float:left;margin-bottom: 5px;\" >\t\t\t\t\t\r\n");
      out.write("\t\t\t  <label style=\" background-color:#D6C7ED;height:100%; width: 10%;border-radius: 3px;float: left;text-align: center;padding-top:3px;\">제목</label>\r\n");
      out.write("\t          <input id=\"title\" name=\"notice_title\" type=\"text\" placeholder=\"제목을 입력하세요\" required style=\"height:100%;width:89.5%; margin-left: 5px;float: left;\">\r\n");
      out.write("\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div style=\"height:300px; width: 100%;margin-top: 5%;\">\t\r\n");
      out.write("\t\t         <label style=\" background-color:#D6C7ED;height:100%; width: 10%;border-radius: 3px;float: left;text-align: center;padding-top:120px;\">내용</label>\r\n");
      out.write("\t\t          <textarea ng-model=\"ele.msg\" id=\"content\" name=\"notice_content\"></textarea>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \t\t\t<div class=\"form-group\" >\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card card-outline card-success\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header\" style=\"height:30px; float: left;width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label style=\" background-color:#D6C7ED;height:100%; width: 10%;border-radius: 3px;text-align: center;padding-top:3px;float: left;\">첨부파일</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-xs \" type=\"button\" id=\"addFileBtn\" style=\"height:100%;margin-left: 5px;width: 30px; background: #D6C7ED;\">+</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div><br><br><br><br>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-footer fileInput\" >\r\n");
      out.write("\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </form>\r\n");
      out.write(" </div>\r\n");
      out.write("  \r\n");
      out.write("  \t<form id=\"jobForm\">\r\n");
      out.write("\t\t  <input type='hidden' name=\"notice_point\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.notice_point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#content').summernote({\r\n");
      out.write("\t\tplaceholder: '내용을 작성하세요.',\r\n");
      out.write("        tabsize: 0,\r\n");
      out.write("\t\theight: 250,\r\n");
      out.write("\t\tfontNames : [ '맑은고딕', 'Arial', 'Arial Black', 'Comic Sans MS', 'Courier New', ],\r\n");
      out.write("\t\tfontNamesIgnoreCheck : [ '맑은고딕' ],\r\n");
      out.write("\t\tfocus: true,\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallbacks: {\r\n");
      out.write("\t\t\tonImageUpload : function(files, editor, welEditable) {\r\n");
      out.write("\t            for (var i = files.length - 1; i >= 0; i--) {\r\n");
      out.write("\t            \tif(files[i].size > 1024*1024*5){\r\n");
      out.write("\t            \t\talert(\"!!!\");\r\n");
      out.write("\t            \t\talert(\"이미지는 5MB 미만입니다.\");\r\n");
      out.write("\t            \t}\r\n");
      out.write("\t            }\r\n");
      out.write("\t            for (var i = files.length - 1; i >= 0; i--) {\r\n");
      out.write("\t            \tsendFile(files[i], this);\r\n");
      out.write("\t            }\r\n");
      out.write("\t        },\r\n");
      out.write("\t        onMediaDelete : function(target) {\r\n");
      out.write("               // deleteFile(target[0].src);                \r\n");
      out.write("\t        \tdeleteFile(target[0].src);\r\n");
      out.write("            }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("function sendFile(file, el) {\r\n");
      out.write("\tvar form_data = new FormData();\r\n");
      out.write("  \tform_data.append(\"file\", file);\r\n");
      out.write("  \t$.ajax({\r\n");
      out.write("    \tdata: form_data,\r\n");
      out.write("    \ttype: \"POST\",\r\n");
      out.write("    \turl: '");
      out.print(request.getContextPath());
      out.write("/uploadImg',\r\n");
      out.write("    \tcache: false,\r\n");
      out.write("    \tcontentType: false,\r\n");
      out.write("    \tenctype: 'multipart/form-data',\r\n");
      out.write("    \tprocessData: false,\r\n");
      out.write("    \tsuccess: function(img_url) {\r\n");
      out.write("      \t\t$(el).summernote('editor.insertImage', img_url);\r\n");
      out.write("    \t}\r\n");
      out.write("  \t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function deleteFile(src) {\r\n");
      out.write("\t\r\n");
      out.write("\tvar splitSrc= src.split(\"/\");\r\n");
      out.write("\tvar fileName = splitSrc[splitSrc.length-1];\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        data: {fileName : fileName},\r\n");
      out.write("        type: \"POST\",\r\n");
      out.write("        url: \"");
      out.print(request.getContextPath());
      out.write("/deleteImg\", \r\n");
      out.write("        cache: false,\r\n");
      out.write("        success: function(resp) {\r\n");
      out.write("            console.log(resp);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$('#notice_regist').on('click', function(e){\r\n");
      out.write("\tvar form = document.regist;\r\n");
      out.write("\tvar jobForm=$('#jobForm');\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tjobForm.find(\"[name='notice_point']\").val($('select[name=\"notice_point\"]').val());\r\n");
      out.write("\t\r\n");
      out.write("\tif(form.title.value==\"\"){\r\n");
      out.write("\t\talert(\"제목은 필수 입니다.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(form.content.value.length>1000){\r\n");
      out.write("\t\talert(\"글자수가 1000자를 초과할 수 없습니다.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tform.submit();\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#notice_char').on('click', function(){\r\n");
      out.write("\tlocation.href=\"notice_list\";\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("<script>\r\n");
      out.write("$('#addFileBtn').on('click',function(event){\r\n");
      out.write("\t\r\n");
      out.write("\tif($('input[name=\"uploadFile\"]').length >=5){\r\n");
      out.write("\t\talert(\"파일추가는 5개까지만 가능합니다.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar input=$('<input>').attr({\"type\":\"file\",\"name\":\"uploadFile\"})\r\n");
      out.write("\t  .css(\"display\",\"inline\"); \r\n");
      out.write("\tvar div=$('<div>').addClass(\"inputRow\");\r\n");
      out.write("\tdiv.append(input).append(\"<button style='border:0;outline:0;' class='badge bg-red' type='button'>X</button>\");\r\n");
      out.write("\tdiv.appendTo('.fileInput');\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('div.fileInput').on('click','div.inputRow > button',function(event){\r\n");
      out.write("\t$(this).parent('div.inputRow').remove();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('.fileInput').on('change','input[type=\"file\"]',function(event){\r\n");
      out.write("\tif(this.files[0].size>1024*1024*40){\r\n");
      out.write("\t\talert(\"파일 용량이 40MB를 초과하였습니다.\");\r\n");
      out.write("\t\tthis.value=\"\";\r\n");
      out.write("\t\t$(this).focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t} \r\n");
      out.write("});\r\n");
      out.write("</script>");
      out.write("</body>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
